### ISSUE TITLE
Delphi 11.3

### ISSUE THREAD

**Issue by thiagoamaralcaragua** [stavarengo/delphi-tdi#14]
bom dia quando uso o componente no delphi 11.3 ao fechar a multijanelas ele fica em branco dai clico em outro form ele fica normal
isso pelo que viu acontece no 11.3 , testei mesma fonte no 10.4 e funciona normal ao fechar a janela

**Comment by thielbit** [comment]
Olá, percebi a mesma situação quando compilado no Delphi 11. 
Se fechar uma aba, todas as demais abertas somem e a tela fica branca. 
Caso clique no local de uma das abas anteriormente abertas, todas que sumiram reaparecem.

**Comment by thielbit** [comment]
Muitíssimo obrigado meu caro, deu certo!

**Comment by stavarengo** [comment]
PR merged.
Obrigado.
